"""WanClaw RPA模块 - Playwright + Selenium 双引擎"""

from .playwright_driver import (
    BrowserPool,
    BrowserDriver,
    RPAManager,
    SmartElementLocator,
    BrowserConfig,
    BrowserType,
    ElementLocator,
    ElementLocatorType,
    get_rpa_manager,
    locate_by_id,
    locate_by_css,
    locate_by_xpath,
    locate_by_text,
    locate_by_placeholder,
    locate_by_role,
)

from .selenium_driver import (
    SeleniumDriver,
    SeleniumPool,
    SeleniumBrowser,
    SeleniumConfig,
    get_selenium_pool,
)

from .engine import (
    RPAEngine,
    ExecutionContext,
    ExecutionResult,
    ExecutionPlan,
    ExecutionStatus,
    ActionType,
    RPALogger,
    get_rpa_engine,
)

from .lobster import (
    LobsterAgent,
    LoopPhase,
    Thought,
    ActionResult,
    ValidationResult,
    LoopContext,
    ToolRegistry,
    get_lobster_agent,
)

from .mcp_adapter import (
    MCPAdapter,
    MCPEndpoint,
    MCPRequest,
    MCPResponse,
    MCPTool,
    MCPConnectionState,
    get_mcp_adapter,
)

__all__ = [
    'BrowserPool',
    'BrowserDriver',
    'RPAManager',
    'SmartElementLocator',
    'BrowserConfig',
    'BrowserType',
    'ElementLocator',
    'ElementLocatorType',
    'get_rpa_manager',
    'locate_by_id',
    'locate_by_css',
    'locate_by_xpath',
    'locate_by_text',
    'locate_by_placeholder',
    'locate_by_role',
    'SeleniumDriver',
    'SeleniumPool',
    'SeleniumBrowser',
    'SeleniumConfig',
    'get_selenium_pool',
    'RPAEngine',
    'ExecutionContext',
    'ExecutionResult',
    'ExecutionPlan',
    'ExecutionStatus',
    'ActionType',
    'RPALogger',
    'get_rpa_engine',
    'LobsterAgent',
    'LoopPhase',
    'Thought',
    'ActionResult',
    'ValidationResult',
    'LoopContext',
    'ToolRegistry',
    'get_lobster_agent',
    'MCPAdapter',
    'MCPEndpoint',
    'MCPRequest',
    'MCPResponse',
    'MCPTool',
    'MCPConnectionState',
    'get_mcp_adapter',
]